# Generated by Django 4.0.6 on 2022-07-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ped', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidodet',
            options={'permissions': [('sup_caja_pedidodet', 'Permisos de Supervisor de Pedidos Detalle')], 'verbose_name': 'Detalle Pedido', 'verbose_name_plural': 'Detalle Pedidos'},
        ),
    ]
