# Generated by Django 4.0 on 2022-09-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_alter_ruta_repartidor'),
        ('ped', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoenc',
            name='repartidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fac.repartidor'),
        ),
    ]
