# Generated by Django 4.1.1 on 2022-09-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ped', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoenc',
            name='facturado',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
