# Generated by Django 4.0.6 on 2022-07-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ped', '0002_alter_pedidodet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoenc',
            options={'permissions': [('sup_caja_pedidoenc', 'Permisos de Supervisor de Pedidos Encabezado')], 'verbose_name': 'Encabezado Pedido', 'verbose_name_plural': 'Encabezado Pedidos'},
        ),
    ]
