# Generated by Django 4.0.6 on 2022-08-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ped', '0003_alter_pedidoenc_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodet',
            name='facturado',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
