# Generated by Django 4.0.6 on 2022-08-30 20:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_ruta_repartidor'),
        ('ped', '0004_pedidodet_facturado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodet',
            name='facturado',
        ),
        migrations.AddField(
            model_name='pedidoenc',
            name='facturado',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='pedidoenc',
            name='fecha_entrega',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoenc',
            name='mail_cliente',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoenc',
            name='mail_repartidor',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoenc',
            name='repartidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fac.repartidor'),
            preserve_default=False,
        ),
    ]
