# Generated by Django 4.0.6 on 2022-09-01 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_ruta_repartidor'),
        ('ped', '0005_remove_pedidodet_facturado_pedidoenc_facturado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoenc',
            name='repartidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fac.repartidor'),
        ),
    ]
