# Generated by Django 4.0.6 on 2022-07-27 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('identificacion', models.CharField(help_text='Identificación', max_length=12, unique=True)),
                ('apellidos', models.CharField(help_text='Apellidos del Repartidor', max_length=30, unique=True)),
                ('nombres', models.CharField(help_text='Nombres del Repartidor', max_length=30, unique=True)),
                ('direccion', models.CharField(help_text='Dirección', max_length=60, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(max_length=250)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Repartidores',
            },
        ),
    ]
