# Generated by Django 4.1.1 on 2022-09-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_alter_cliente_segmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(choices=[('Corporativo-Empresarial-Mayorista', 'Corporativo-Empresarial-Mayorista'), ('Natural-Detail-Minorista', 'Natural-Detail-Minorista'), ('Institucional-Público-Fundaciones', 'Institucional-Público-Fundaciones'), ('Tienda-Minimercado-Negocio', 'Tienda-Minimercado-Negocio')], default='Natural-Detail-Minorista', max_length=60),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Jurídica', 'Jurídica')], default='Natural-Detail-Minorista', max_length=10),
        ),
    ]
