# Generated by Django 4.0 on 2022-08-31 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fac.repartidor'),
        ),
    ]
