# Generated by Django 4.1.1 on 2022-09-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_alter_cliente_segmento_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, help_text='Contacto', max_length=60),
        ),
    ]
